[file]
	name = "File"
	variable = [
		[ 0, "Open" ],
		[ 1, "Save" ],
		[ 2, "Save As" ],
		[ 3, "Export" ],
	]
[options]
	name = "Options"
	variable = [
		[ 0, "Yes" ],
		[ 1, "No" ],
	]
[behaviour1]
	name = "Env 1"
	variable = [
		[ 0, "Overworld" ],
		[ 1, "Dungeon"   ],
		[ 2, "House"     ],
		[ 5, "Boss Room" ],
	]
[behaviour2]
	name = "Env 2"
	variable = [
		[ 0, "Default"     ],
		[ 1, "Cold"        ],
		[ 2, "Hot"         ],
		[ 3, "Hot (Timer)" ],
		[ 4, "Comfy"       ],
	]